### ISSUE TITLE
Sort by download?

### ISSUE THREAD

**Issue by doctordns** [jdhitsolutions/PSGalleryReport#1]
Would it make sense to have a summary of the most downloaded packages?

**Comment by doctordns** [comment]
What I meant was to have the newest modules sorted both by name and by download count?

**Comment by jdhitsolutions** [comment]
A report of the latest X number of modules published sorted by download count may be misleading or not valuable. If it is a brand new module there will be 0 to a very low number of downloads. I'm not sure how valuable that would be. It wouldn't tell me anything about the quality of the module.

**Comment by jdhitsolutions** [comment]
Is there anything lacking in the current download reports?

**Comment by jdhitsolutions** [comment]
Closing this as I think the current Downloads report meets the issue.
