### ISSUE TITLE
Include Functions and Cmdlets

### ISSUE THREAD

**Issue by ThomasNieto** [jdhitsolutions/PSGalleryReport#6]
I'd like to use the PSGalleryData.zip to a primer for my PS command not found cache. The problem is that the data currently doesn't store information about included functions and cmdlets. This data is stored in the `AdditionalMetadata` property under `Functions` and `Cmdlets` if a module doesn't include one or both then the key doesn't exist. If you do include this data currently the value is a string, for it to be easier to consume I'd recommend splitting the string on space to turn it into a collection for your json file.

I'm currently building a local cache in memory which takes time to build querying PSGallery. Using your already generated report would reduce the time greatly. Here is the example of what the cache is used for:

![image](https://github.com/user-attachments/assets/9129b65f-5075-4f4b-beeb-8dc436f36852)

**Comment by jdhitsolutions** [comment]
I am actually trying to make this repo smaller! ;-) I would suggest you take the relevant lines from `run.ps1` and adjust them to meet your needs. You can create a data file on your own and not rely on this repository. Or fork the repo and make adjustments as needed.

**Comment by ThomasNieto** [comment]
That's fine, I'll go ahead and close the issue.

**Comment by ThomasNieto** [comment]
@jdhitsolutions have you looked into LFS to reduce the size of the repo?

**Comment by jdhitsolutions** [comment]
I think I have it set up for the repo. This issue seems to be the commit history and blob storage for the PDFs that are created every time the GitHub action runs. I will freely admit to shortcomings in git and GitHub expertise,

**Comment by ThomasNieto** [comment]
I'm not that familiar with it either but it looks like you could add `*.pdf` to lfs and then migrate those to reduce space.

**Comment by jdhitsolutions** [comment]
I forgot that I removed PDFs, even though I did configure them for LFS.
